name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: test
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        include:
          - os: linux
            image: ubuntu-latest
          - os: macos
            image: macos-latest
          - os: windows
            image: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install linux
        if: ${{ matrix.os == 'linux' }}
        run: |
          set -ex
          sudo apt install gpg
          wget https://github.com/mozilla/sops/releases/download/v3.6.1/sops_3.6.1_amd64.deb
          sudo dpkg -i sops*
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin

      - name: Install macos
        if: ${{ matrix.os == 'macos' }}
        run: |
          set -ex
          brew install gpg sops kustomize

      # Chocolatey times out, so scoop it is
      - name: Install windows
        if: ${{ matrix.os == 'windows' }}
        run: |
          Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
          scoop install gnupg sops kustomize
          echo "C:\Users\runneradmin\scoop\shims" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: Check for kustomize
        if: ${{ matrix.os == 'windows' }}
        run: |
          echo $env:PATH
          get-command kustomize

      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Run clippy
        run: cargo clippy --verbose
      - name: Run rustfmt
        run: cargo fmt -- --check
